# Generated by Django 5.2.8 on 2025-11-19 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='raw',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
